In [1]:
import time
import random
from math import *
import operator
import pandas as pd
import numpy as np

# import plotting libraries
import matplotlib
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline 

import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)

# import the ML algorithm
from sklearn.linear_model import LinearRegression
#from pandas.core import datetools

from statsmodels.tools.eval_measures import rmse

# import libraries for model validation
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# import libraries for metrics and reporting
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import mean_squared_error, r2_score

from sklearn import datasets, linear_model

In [2]:
plt.rcParams['figure.figsize'] = (14, 5)

In [3]:
# Reading Data
data = pd.read_csv(r'E:\MYLEARN\2-ANALYTICS-DataScience\datasets\headsize.csv')
data.head()

   Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [5]:
# Collecting X and Y
X = data['Head Size(cm^3)'].values
Y = data['Brain Weight(grams)'].values

In [6]:
X

array([4512, 3738, 4261, 3777, 4177, 3585, 3785, 3559, 3613, 3982, 3443,
       3993, 3640, 4208, 3832, 3876, 3497, 3466, 3095, 4424, 3878, 4046,
       3804, 3710, 4747, 4423, 4036, 4022, 3454, 4175, 3787, 3796, 4103,
       4161, 4158, 3814, 3527, 3748, 3334, 3492, 3962, 3505, 4315, 3804,
       3863, 4034, 4308, 3165, 3641, 3644, 3891, 3793, 4270, 4063, 4012,
       3458, 3890, 4166, 3935, 3669, 3866, 3393, 4442, 4253, 3727, 3329,
       3415, 3372, 4430, 4381, 4008, 3858, 4121, 4057, 3824, 3394, 3558,
       3362, 3930, 3835, 3830, 3856, 3249, 3577, 3933, 3850, 3309, 3406,
       3506, 3907, 4160, 3318, 3662, 3899, 3700, 3779, 3473, 3490, 3654,
       3478, 3495, 3834, 3876, 3661, 3618, 3648, 4032, 3399, 3916, 4430,
       3695, 3524, 3571, 3594, 3383, 3499, 3589, 3900, 4114, 3937, 3399,
       4200, 4488, 3614, 4051, 3782, 3391, 3124, 4053, 3582, 3666, 3532,
       4046, 3667, 2857, 3436, 3791, 3302, 3104, 3171, 3572, 3530, 3175,
       3438, 3903, 3899, 3401, 3267, 3451, 3090, 3413, 3323, 3680, 3439,
       3853, 3156, 3279, 3707, 4006, 3269, 3071, 3779, 3548, 3292, 3497,
       3082, 3248, 3358, 3803, 3566, 3145, 3503, 3571, 3724, 3615, 3203,
       3609, 3561, 3979, 3533, 3689, 3158, 4005, 3181, 3479, 3642, 3632,
       3069, 3394, 3703, 3165, 3354, 3000, 3687, 3556, 2773, 3058, 3344,
       3493, 3297, 3360, 3228, 3277, 3851, 3067, 3692, 3402, 3995, 3318,
       2720, 2937, 3580, 2939, 2989, 3586, 3156, 3246, 3170, 3268, 3389,
       3381, 2864, 3740, 3479, 3647, 3716, 3284, 4204, 3735, 3218, 3685,
       3704, 3214, 3394, 3233, 3352, 3391], dtype=int64)

In [8]:
m = len(X)

In [9]:
X.reshape((m, 1))

array([[4512],
       [3738],
       [4261],
       [3777],
       [4177],
       [3585],
       [3785],
       [3559],
       [3613],
       [3982],
       [3443],
       [3993],
       [3640],
       [4208],
       [3832],
       [3876],
       [3497],
       [3466],
       [3095],
       [4424],
       [3878],
       [4046],
       [3804],
       [3710],
       [4747],
       [4423],
       [4036],
       [4022],
       [3454],
       [4175],
       [3787],
       [3796],
       [4103],
       [4161],
       [4158],
       [3814],
       [3527],
       [3748],
       [3334],
       [3492],
       [3962],
       [3505],
       [4315],
       [3804],
       [3863],
       [4034],
       [4308],
       [3165],
       [3641],
       [3644],
       [3891],
       [3793],
       [4270],
       [4063],
       [4012],
       [3458],
       [3890],
       [4166],
       [3935],
       [3669],
       [3866],
       [3393],
       [4442],
       [4253],
       [3727],
       [3329],
       [3415],
       [3372],
       [4430],
       [4381],
       [4008],
       [3858],
       [4121],
       [4057],
       [3824],
       [3394],
       [3558],
       [3362],
       [3930],
       [3835],
       [3830],
       [3856],
       [3249],
       [3577],
       [3933],
       [3850],
       [3309],
       [3406],
       [3506],
       [3907],
       [4160],
       [3318],
       [3662],
       [3899],
       [3700],
       [3779],
       [3473],
       [3490],
       [3654],
       [3478],
       [3495],
       [3834],
       [3876],
       [3661],
       [3618],
       [3648],
       [4032],
       [3399],
       [3916],
       [4430],
       [3695],
       [3524],
       [3571],
       [3594],
       [3383],
       [3499],
       [3589],
       [3900],
       [4114],
       [3937],
       [3399],
       [4200],
       [4488],
       [3614],
       [4051],
       [3782],
       [3391],
       [3124],
       [4053],
       [3582],
       [3666],
       [3532],
       [4046],
       [3667],
       [2857],
       [3436],
       [3791],
       [3302],
       [3104],
       [3171],
       [3572],
       [3530],
       [3175],
       [3438],
       [3903],
       [3899],
       [3401],
       [3267],
       [3451],
       [3090],
       [3413],
       [3323],
       [3680],
       [3439],
       [3853],
       [3156],
       [3279],
       [3707],
       [4006],
       [3269],
       [3071],
       [3779],
       [3548],
       [3292],
       [3497],
       [3082],
       [3248],
       [3358],
       [3803],
       [3566],
       [3145],
       [3503],
       [3571],
       [3724],
       [3615],
       [3203],
       [3609],
       [3561],
       [3979],
       [3533],
       [3689],
       [3158],
       [4005],
       [3181],
       [3479],
       [3642],
       [3632],
       [3069],
       [3394],
       [3703],
       [3165],
       [3354],
       [3000],
       [3687],
       [3556],
       [2773],
       [3058],
       [3344],
       [3493],
       [3297],
       [3360],
       [3228],
       [3277],
       [3851],
       [3067],
       [3692],
       [3402],
       [3995],
       [3318],
       [2720],
       [2937],
       [3580],
       [2939],
       [2989],
       [3586],
       [3156],
       [3246],
       [3170],
       [3268],
       [3389],
       [3381],
       [2864],
       [3740],
       [3479],
       [3647],
       [3716],
       [3284],
       [4204],
       [3735],
       [3218],
       [3685],
       [3704],
       [3214],
       [3394],
       [3233],
       [3352],
       [3391]], dtype=int64)

In [10]:
m = len(X)
X = X.reshape((m, 1))

# Model Intialization
reg = LinearRegression()

# Data Fitting
reg = reg.fit(X, Y)

# Y Prediction
Y_pred = reg.predict(X)

In [23]:
# Model Evaluation
rmse = np.sqrt(mean_squared_error(Y, Y_pred))
r2   = reg.score(X, Y)

print("RMSE", end=' ')
print(rmse)
print("R2 Score", end=' ')
print(r2)

RMSE 72.1206213783709
R2 Score 0.639311719957